In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving bank_Data.xlsx to bank_Data.xlsx

In [ ]:
import pandas as pd

df = pd.read_excel("bank_Data.xlsx")
df.head()

,Transaction_ID,Date,Customer_ID,Customer_Name,Account_Type,Transaction_Type,Amount,Branch,Channel,Loan_Status,Credit_Score
0,TXN000001,2024-01-01,CUST0001,Aarav Sharma,Savings,Debit,2450.75,Mumbai,ATM,Approved,782
1,TXN000002,2024-01-02,CUST0002,Priya Patel,Current,Credit,18500.00,Delhi,Online,Rejected,641
2,TXN000003,2024-01-03,CUST0003,Rahul Verma,Credit,Debit,950.50,Bengaluru,Bank,Approved,815
3,TXN000004,2024-01-04,CUST0004,Sneha Reddy,Savings,Credit,4200.25,Hyderabad,Online,Approved,734
4,TXN000005,2024-01-05,CUST0005,Karan Singh,Current,Debit,12750.00,Chennai,ATM,Rejected,602

In [ ]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Transaction_ID      0
Date                0
Customer_ID         0
Customer_Name       0
Account_Type        0
Transaction_Type    0
Amount              0
Branch              0
Channel             0
Loan_Status         0
Credit_Score        0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df['Month'] = df['Date'].dt.month

In [ ]:
print(df.head())

  Transaction_ID       Date Customer_ID Customer_Name Account_Type  \
0      TXN000001 2024-01-01    CUST0001  Aarav Sharma      Savings
1      TXN000002 2024-01-02    CUST0002   Priya Patel      Current
2      TXN000003 2024-01-03    CUST0003   Rahul Verma       Credit
3      TXN000004 2024-01-04    CUST0004   Sneha Reddy      Savings
4      TXN000005 2024-01-05    CUST0005   Karan Singh      Current

  Transaction_Type    Amount     Branch Channel Loan_Status  Credit_Score  \
0            Debit   2450.75     Mumbai     ATM    Approved           782
1           Credit  18500.00      Delhi  Online    Rejected           641
2            Debit    950.50  Bengaluru    Bank    Approved           815
3           Credit   4200.25  Hyderabad  Online    Approved           734
4            Debit  12750.00    Chennai     ATM    Rejected           602

   Month
0      1
1      1
2      1
3      1
4      1

In [ ]:
df.to_excel("bank_Data.xlsx", index=False)

print("Data cleaning completed successfully!")

Data cleaning completed successfully!

In [ ]:
df.groupby('Account_Type')['Amount'].sum()

Account_Type
Credit      100290.40
Current     312730.89
Savings    1478570.99
Name: Amount, dtype: float64

In [ ]:
df.groupby('Branch')['Amount'].sum()

Branch
Ahmedabad    138064.89
Bengaluru    230634.69
Chennai      217404.30
Delhi        158886.70
Hyderabad    135800.90
Jaipur       224181.60
Kolkata      241696.50
Lucknow      194662.90
Mumbai       191680.15
Pune         158579.65
Name: Amount, dtype: float64

In [ ]:
df.groupby('Month')['Amount'].sum()

Month
1    269107.13
2    268763.80
3    267652.25
4    299326.10
5    300532.05
6    299666.00
7    186544.95
Name: Amount, dtype: float64

In [ ]:
df.groupby('Customer_ID')['Amount'].sum().sort_values(ascending=False).head
(10)

10

In [ ]:
df['Loan_Status'].value_counts(normalize=True) * 100

Loan_Status
Approved    74.5
Rejected    25.5
Name: proportion, dtype: float64

In [ ]:
df['Channel'].value_counts()

Channel
ATM       67
Online    67
Bank      66
Name: count, dtype: int64